<?php

namespace Deployer;

/**
 * repository
 *
 * Set the repository URL - this is generated by Gitlab CI to include a deploy token
 */
if (getenv('CI_REPOSITORY_URL')) {
	set('repository', getenv('CI_REPOSITORY_URL'));
}

/**
 * keep_releases
 *
 * How many releases to keep
 */
set('keep_releases', 3);

/**
 * shared_files
 *
 * Add .env as a shared file
 */
set('shared_files', array_merge(get('shared_files'), ['.env']));

/**
 * writable_dirs
 *
 * Which folders are writeable?
 */
set(
	'writable_dirs',
	[
		'var',
		get('web_path') . 'typo3conf',
		get('web_path') . 'typo3temp',
		get('web_path') . 'uploads',
		get('web_path') . 'fileadmin',
	]
);

/**
 * clear_paths
 *
 * What folders get removed from live?
 */
set(
	'clear_paths',
	array_merge(
		get('clear_paths'),
		[
			'.gitlab',
			'.gitlab-ci.yml',
			'build/',
			'gulpfile.js',
			'package.json',
			'package-lock.json',
		]
	)
);
