<?php

namespace Deployer;

/**
 * driver_typo3cms
 * @package deployer-extended-typo3
 *
 * Use typo3 as the driver - will get db details from typo3cms command
 */
set('driver_typo3cms', true);

/**
 * repository
 * @package deployer
 *
 * Set the repository URL - this is generated by Gitlab CI to include a deploy token
 */
if (getenv('CI_REPOSITORY_URL')) {
	set('repository', getenv('CI_REPOSITORY_URL'));
}

/**
 * web_path
 * @package deployer-extended
 *
 * Use the web path from composer
 */
if (isset(
	$this->composer['extra'],
	$this->composer['extra']['typo3/cms'],
	$this->composer['extra']['typo3/cms']['web-dir']
)) {
	set('web_path', rtrim($this->composer['extra']['typo3/cms']['web-dir'], '/') . '/');
}

/**
 * local_host
 *
 * @package deployer-extended-database
 *
 * If you just run "deploy" what happens?
 *
 * Check if file doesn't exist - e.g. deploying via CI
 * This is needed for the database backup
 */
if (!file_exists(getcwd() . '/.env')) {
	set('local_host', 'local');
}

/**
 * composer_channel
 * @package deployer-extended
 *
 * What composer version?
 */
set('composer_channel', 2);

/**
 * shared_files
 * @package deployer
 *
 * Add .env as a shared file
 */
set('shared_files', array_merge(get('shared_files'), ['.env']));

/**
 * keep_releases
 * @package deployer
 *
 * How many releases to keep
 */
set('keep_releases', 3);

/**
 * db_allow_push_live
 * @package deployer-extended-database
 *
 * Allow db to be pushed live (with confirmation)
 */
set('db_allow_push_live', true);

/**
 * media_allow_push_live
 * @package deployer-extended-media
 *
 * Allow media to be pushed live (with confirmation)
 */
set('media_allow_push_live', true);

/**
 * writable_chmod_mode
 * @package deployer
 *
 * What permissions should "writable_dirs" have?
 */
set('writable_chmod_mode', '0775');

/**
 * writable_recursive
 * @package deployer
 *
 * Use recursive mode (-R)?
 */
set('writable_recursive', true);

/**
 * env
 * @package deployer
 *
 * Remote environment variables.
 */
set('env', [
	'COMPOSER_AUTH' => getenv('COMPOSER_AUTH'),
]);

/**
 * writable_dirs
 * @package deployer
 *
 * Which folders are writeable?
 */
set(
	'writable_dirs',
	[
		'var',
		get('web_path') . 'typo3conf',
		get('web_path') . 'typo3temp',
		get('web_path') . 'uploads',
		get('web_path') . 'fileadmin',
	]
);

/**
 * clear_paths
 * @package deployer
 *
 * What folders get removed from live?
 */
set(
	'clear_paths',
	array_merge(
		get('clear_paths'),
		[
			'.gitlab',
			'.gitlab-ci.yml',
			'build/',
			'gulpfile.js',
			'package.json',
			'package-lock.json',
		]
	)
);
